# Dockerfile
FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install python3-venv -y
RUN /usr/sbin/python3 -m venv dataops
RUN source dataops/bin/activate
RUN pip3 install django
RUN django-admin startproject dataops
